### ISSUE TITLE
"fork() function is unimplemented on this machine"

### ISSUE THREAD

**Issue by farlin** [justinko/sunspot-rails-tester#8]
Hi there,

I am trying to use Rspec to test a model function that executes search.
The function works properly when being tested using ui. But as soon as I try to switch the :solr => true,
it throws error with "fork() function is unimplemented on this machine"

``` ruby
  it "searches", :solr => true do
    # if I search for 'help' 
    result = Model.search ({:q => ["help"]})
    # "we are expecting 10 instances"
    result.count.should == 10
  end
```

Environment details:

```
win 64bit
Ruby 1.9.3
Rails 3.2.13
```

Stacktrace:

```
Failure/Error: Unable to find matching line from backtrace
    NotImplementedError:
    fork() function is unimplemented on this machine
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sunspot-rails-tester-1.0.0/lib/sunspot/rails/tester.rb:18:in `fork' 
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sunspot-rails-tester-1.0.0/lib/sunspot/rails/tester.rb:18:in `start_original_sunspot_session'
C:/APP_DIR/spec/spec_helper.rb:47:in `block (2 levels) in <top (required)>'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:237:in `instance_eval'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:237:in `instance_eval'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/hooks.rb:21:in `run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/hooks.rb:66:in `block in run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/hooks.rb:66:in `each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/hooks.rb:66:in `run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/hooks.rb:418:in `run_hook'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:334:in `run_before_each_hooks'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:300:in `run_before_each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:113:in `block in run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:254:in `with_around_each_hooks'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:111:in `run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:390:in `block in run_examples'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:386:in `map'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:386:in `run_examples'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:371:in `run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:28:in `map'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:28:in `block in run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/reporter.rb:34:in `report'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:25:in `run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/runner.rb:80:in `run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/runner.rb:17:in `block in autorun'
```

Is there something I'm missing, or is it not supported for windows? 
Any help would be much appreciated!

Cheers!

**Comment by Pauloparakleto** [comment]
See the [Rails test guides, section 3.2](https://guides.rubyonrails.org/testing.html#parallel-testing-with-threads) to change workers -- which use the said fork(method) to paralleled processes -- to threads. This last one use another method to parallel processes. Also take a look on the beginning of the section 3, which describes how the tests are made.
I have used a WSL2 to run Rails. However the local test needs the jruby to be executed in somewhat.
